name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: "checkout Source ${{ matrix.node-version }}"
        uses: actions/checkout@v4
      - name: "Login to Dockerhub"
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
      - name: "Build Docker image"
        run: docker build -t naveen9700/nodejs-app .
      - name: "Tag the image"
        run:  docker tag nodejs-app naveen9700/nodejs-app:latest
      - name: "Publish image to Dockerhub"
        run: docker push naveen9700/nodejs-app:lastet 
  
